### PR TITLE
.NET 4.5 Support for Travis CI

### PR DESCRIPTION
**Pull request by gmt2001**
This branch updates the .travis.yml file to use the direct C# language support in Travis CI, which provides support for .NET 4.5 through Mono version 3.8.0 and later

### CODE REVIEW

**Comment by gmt2001** [comment]
Note that the HintPath will have to be fixed with this as the current one will fail to resolve.

The correct HintPath will likely be **$(SolutionDir)/packages/...**

**Comment by meebey** [comment]
Does the new platform allow to still run commands? make distcheck is testing if the make based build still works...

**Comment by meebey** [comment]
@gmt2001 after reading https://docs.travis-ci.com/user/languages/csharp/#Script it seems like the script: block can stay and it should build both ways.

**Comment by gmt2001** [comment]
I got autotools added back in and corrected the HintPath

**Comment by meebey** [comment]
Merged with some small changes in 58aa5fe

Thanks for your contribution!

**Pull request closed without merging**
